# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章详情')),
                ('viewedTimes', models.IntegerField(verbose_name='浏览次数')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '文章',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='articleclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='文章分类名称')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '文章分类',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('link', models.CharField(blank=True, max_length=50, verbose_name='链接地址（可为空）')),
                ('caption', models.CharField(blank=True, max_length=500, null=True, verbose_name='子标题')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '轮播管理',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='案例名称')),
                ('content', models.TextField(verbose_name='介绍详情')),
                ('viewedTimes', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('href', models.CharField(max_length=50, verbose_name='友情链接')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '案例',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='资质名称')),
                ('content', models.TextField(verbose_name='介绍详情')),
                ('viewedTimes', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '设备',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='certificateclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='证书分类名称')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '证书分类',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('content', models.TextField(verbose_name='介绍详情')),
                ('viewedTimes', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '设备',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='facilityclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='设备分类名称')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '设备分类',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='friendlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='友情链接名称')),
                ('href', models.CharField(max_length=50, verbose_name='友情链接')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '友情链接',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='职位名称')),
                ('content', models.TextField(verbose_name='介绍详情')),
                ('viewedTimes', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('href', models.CharField(max_length=50, null=True, verbose_name='友情链接')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '案例',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('caption', models.CharField(blank=True, max_length=34, null=True, verbose_name='内容')),
                ('filepath', models.CharField(blank=True, max_length=200, null=True, verbose_name='文件地址')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '图片库',
                'verbose_name': '图片',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('content', models.TextField(verbose_name='介绍详情')),
                ('viewedTimes', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
                ('imgs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.picture')),
            ],
            options={
                'verbose_name': '产品',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='productclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='产品分类名称')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '产品分类',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='syspara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, verbose_name='键')),
                ('value', models.CharField(blank=True, max_length=3400, null=True, verbose_name='值')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '系统参数们',
                'verbose_name': '系统参数',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, unique=True, verbose_name='登录名')),
                ('pwd', models.CharField(blank=True, max_length=34, null=True, verbose_name='密码')),
                ('salt', models.CharField(blank=True, max_length=32, null=True, verbose_name='密码盐值')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户类型')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
                ('avt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.picture')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': '用户资料表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('caption', models.CharField(blank=True, max_length=34, null=True, verbose_name='内容')),
                ('filepath', models.CharField(blank=True, max_length=200, null=True, verbose_name='文件地址')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '视频库',
                'verbose_name': '视频',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productclass'),
        ),
        migrations.AddField(
            model_name='facility',
            name='imgs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.picture'),
        ),
        migrations.AddField(
            model_name='facility',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productclass'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='imgs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.picture'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.certificateclass'),
        ),
        migrations.AddField(
            model_name='case',
            name='imgs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.picture'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='imgs',
            field=models.ManyToManyField(to='core.picture'),
        ),
        migrations.AddField(
            model_name='article',
            name='imgs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.picture'),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.certificateclass'),
        ),
    ]
