# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articleclass'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facilityclass'),
        ),
    ]
