# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170419_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='syspara',
            name='imgs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.picture'),
        ),
    ]
