# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_syspara_en_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.CharField(max_length=150, verbose_name='邮箱')),
                ('tel', models.CharField(max_length=50, verbose_name='电话')),
                ('info', models.CharField(max_length=5000, verbose_name='信息')),
            ],
            options={
                'verbose_name': '联系我们表',
                'verbose_name_plural': '联系我们表',
                'ordering': ['id'],
            },
        ),
    ]
