# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='content',
        ),
        migrations.AddField(
            model_name='facility',
            name='madefac',
            field=models.CharField(max_length=50, null=True, verbose_name='制作厂商'),
        ),
        migrations.AddField(
            model_name='facility',
            name='num',
            field=models.CharField(max_length=50, null=True, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='facility',
            name='para',
            field=models.CharField(max_length=100, null=True, verbose_name='参数'),
        ),
        migrations.AddField(
            model_name='facility',
            name='unit',
            field=models.CharField(max_length=50, null=True, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='facility',
            name='usage',
            field=models.CharField(max_length=50, null=True, verbose_name='用途'),
        ),
    ]
