# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170506_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='caseclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='证书分类名称')),
                ('language', models.CharField(default='zh', max_length=34, verbose_name='语言 zh | en')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '证书分类',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='content',
            field=models.CharField(max_length=50, verbose_name='介绍详情'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='madefac',
            field=models.CharField(max_length=80, null=True, verbose_name='制作厂商'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='para',
            field=models.CharField(max_length=500, null=True, verbose_name='参数'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='usage',
            field=models.CharField(max_length=500, null=True, verbose_name='用途'),
        ),
    ]
