# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170506_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.caseclass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caseclass',
            name='name',
            field=models.CharField(max_length=50, verbose_name='成功案例分类名称'),
        ),
    ]
