# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170507_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brief',
            field=models.CharField(default='', max_length=500, verbose_name='简介'),
        ),
    ]
