# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='img',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.picture'),
            preserve_default=False,
        ),
    ]
