# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170509_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syspara',
            name='en_key',
            field=models.CharField(max_length=50, null=True, verbose_name='英文键'),
        ),
        migrations.AlterField(
            model_name='syspara',
            name='key',
            field=models.CharField(max_length=50, verbose_name='键'),
        ),
    ]
