# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170509_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='href',
            field=models.CharField(max_length=200, verbose_name='友情链接'),
        ),
    ]
