# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170519_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-type'], 'verbose_name': '案例'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['-type'], 'verbose_name': '设备'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-type'], 'verbose_name': '产品'},
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500, verbose_name='文章标题'),
        ),
    ]
